### ISSUE TITLE
Problems interfacing with task export

### ISSUE THREAD

**Issue by regnat** [rampantmonkey/twui#58]
In my computer -- and according to the [taskwarrior documentation](https://github.com/rampantmonkey/twui), `task export` outputs consits of json object per line, like this:
```
{"id":1,"description":"desc1","entry":"...","modified":"...","project":"divers","status":"pending","tags":["myTag"],"urgency":2.50137}
{"id":2,"description":"desc2","entry":"...","modified":"...","project":"divers","status":"pending","tags":["myTag"],"urgency":2.50137}
{"id":3,"description":"desc3","entry":"...","modified":"...","project":"divers","status":"pending","tags":["myTag2"],"urgency":2.50137}
```

Then, twui adds brackets around to make it looks like a json array, but it fails because it lacks a coma at the end of each object, and I got a `[SyntaxError: Unexpected token {]` message from the json parser (dunno why it seems to be working everywhere else, maybe my javascript version got a more rigid json parser).
The correct array is
```
[
{"id":1,"description":"desc1","entry":"...","modified":"...","project":"divers","status":"pending","tags":["myTag"],"urgency":2.50137},
{"id":2,"description":"desc2","entry":"...","modified":"...","project":"divers","status":"pending","tags":["myTag"],"urgency":2.50137},
{"id":3,"description":"desc3","entry":"...","modified":"...","project":"divers","status":"pending","tags":["myTag2"],"urgency":2.50137},
]
```
and the parser gets this (notice the absence of comas at the end of each line):
```
[
{"id":1,"description":"desc1","entry":"...","modified":"...","project":"divers","status":"pending","tags":["myTag"],"urgency":2.50137}
{"id":2,"description":"desc2","entry":"...","modified":"...","project":"divers","status":"pending","tags":["myTag"],"urgency":2.50137}
{"id":3,"description":"desc3","entry":"...","modified":"...","project":"divers","status":"pending","tags":["myTag2"],"urgency":2.50137}
]
```

There's a taskwarrior option (json.array) which enables to directly format output as a correct json array. I think it should be better to use it instead trying to build it manually to avoid those problems.

**Comment by rampantmonkey** [comment]
Thanks for the report and suggestion.

**Comment by linuxcaffe** [comment]
In the upcoming task v2.5.0, json.array is the default!

**Comment by x4121** [comment]
In your fix you changed `JSON.parse('[' + value + ']').map(function(row) ...` to `raw.map(function(row) ...`. For me this throws "TypeError: raw.map is not a function". I never programmed in JavaScript, but shouldn't it be something like `JSON.parse(value).map(function(row) ...`? At least that's fixing it for me.
